T5-288 Update shopify form
thirdandgrove/thirdandgrove-com-gatsby pull request #453
Opened 2021-06-16 00:36 UTC by naeluh

2021-06-16 12:08 UTC, jds-tag requested changes
Grammar nits but lgtm otherwise!

2021-06-16 12:08 UTC, jds-tag commented on src/templates/insights.js
> +                header='Submit your email to access our free ebook'
Do we want a period here?

2021-06-16 12:08 UTC, jds-tag commented on src/templates/insights.js
> +                confirmMessage='Thanks for you submission!'
"Thank you for your submission!"

2021-06-21 18:54 UTC, jds-tag commented on src/templates/insights.js
> +                confirmMessage='Thank you for you submission!'
`for your submission` (not "you").

2021-06-21 18:58 UTC, jds-tag approved these changes
LGTM!

2021-07-06 21:23 UTC, jds-tag reviewed
Some nits.

2021-07-06 21:23 UTC, jds-tag commented on src/components/SplitHeader/SplitHeader.js
> +
This new line is cool but there are no new lines anywhere else. Should this be consistent?

2021-07-06 21:23 UTC, jds-tag commented on src/components/SplitHeader/SplitHeader.js
> +    div.left {
Not a dealbreaker but does `left` and `right` make the most sense semantically if they stack on mobile?

2021-07-06 21:23 UTC, jds-tag commented on src/components/SplitHeader/SplitHeader.js
> +              text='Download E-book'
Is it `ebook` or `E-book`? Make it consistent.

2021-07-06 22:08 UTC, naeluh commented on src/components/SplitHeader/SplitHeader.js
> +              text='Download E-book'
Updated the names thanks!

2021-07-06 22:09 UTC, naeluh commented on src/components/SplitHeader/SplitHeader.js
> +    div.left {
Updated the names thanks!

2021-07-06 22:10 UTC, naeluh commented on src/components/SplitHeader/SplitHeader.js
> +
Update the spacing thanks!

2021-07-07 16:34 UTC, jds-tag approved these changes
LGTM! Just noting that `E-book` or `E-Book` is the appropriate usage (saw it in an Acquia email this morning) so just make sure anytime `E-book` is written out it has the hyphen. Thanks!

2021-07-07 16:36 UTC, merged