T5-423: Add new form
thirdandgrove/thirdandgrove-com-gatsby pull request #622
Opened 2023-08-30 21:54 UTC by naeluh

2023-08-30 22:28 UTC, brs14ku commented on src/components/Form/Form.js
> +    if (formResponse.ok) {
If we're setting `hasSubmitted` to show as an error to limit multiple submissions, why even reset the form? Should we just hide on success?

2023-08-30 22:31 UTC, brs14ku commented on static/functions/submission-created.js
> +    const fields = {
Can we make these `env` items instead?

2023-08-30 22:32 UTC, brs14ku requested changes
Left you a few comments/q's!

2023-09-01 00:37 UTC, naeluh commented
Hey @brs14ku thanks ! I actually updated this over in another PR and I am going to close this one since this has to go into develop. https://github.com/thirdandgrove/thirdandgrove-com-gatsby/pull/624 I updated the code in the ways that you suggested let me know if that works Thanks !

2023-09-01 19:05 UTC, brs14ku commented
> Hey @brs14ku thanks ! I actually updated this over in another PR and I am going to close this one since this has to go into develop. #624 I updated the code in the ways that you suggested let me know if that works Thanks !

Approved the other. Thanks!

2023-09-01 23:30 UTC, closed without merging